#!/bin/bash
#------------------------------------------------------------------------------
#Variable definition
#------------------------------------------------------------------------------

DEPLOY_JAR="Boom-project-assembly-1.0.0-SNAPSHOT.jar"


#------------------------------------------------------------------------------
#script
#------------------------------------------------------------------------------
echo $(date +"%Y-%m-%d:%Hh:%Mm:%Ss") 'Running flat jar in cluster'

#use when save is Parquet format a JDBC scheme
#spark-submit --driver-memory 11g "$DEPLOY_JAR"  ${*}

spark-submit "$DEPLOY_JAR"  ${*}

echo $(date +"%Y-%m-%d:%Hh:%Mm:%Ss") 'End of running flat jar in cluster'

#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
